language: cpp

sudo: true

os: linux

compiler:
  - gcc

before_install:
  # so that adjusted PATH propagates into sudo
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - sudo apt-get update
  - sudo apt-get install flawfinder

install:
  - git clone http://www.github.com/gmkurtzer/singularity
  - cd singularity
  - ./autogen.sh
  - ./configure --prefix=/usr/local
  - make
  - sudo make install

script:
  - sudo singularity create image.img
  - sudo singularity bootstrap image.img Singularity
